[package]
name = "rust"
version = "0.1.0"
authors = ["abhaypande"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time-test = "0.2.2"